virtual bool initScenePlayer(SGE_ScenePlayerInfo& info);
virtual bool scenePlayerUpLevel(S32 level);
virtual bool scenePlayerAddCurrentQuest(S32 questId);
virtual bool scenePlayerDelCurrentQuest(S32 questId);
virtual bool scenePlayerAddAcceptableQuest(S32 questId);
virtual bool scenePlayerDelAcceptableQuest(S32 questId);
virtual bool openScene(S32 sceneId);
virtual bool joinBattle();
virtual bool finishBattle();
virtual bool transforScene(S32 sceneId);
virtual bool transforSceneByEntry(S32 sceneId, S32 entryId);
virtual bool backHomeScene();
virtual bool sceneLoaded();
virtual bool move(COM_FPosition& pos);
virtual bool moveToNpc(S32 npcid);
virtual bool moveToNpc2(NpcType type);
virtual bool moveToZone(S32 sceneId, S32 zoneId);
virtual bool autoBattle();
virtual bool stopMove();
virtual bool addFollow(S32 scenePlayerId);
virtual bool delFollow(S32 scenePlayerId);
virtual bool delFollows();
virtual bool addFollows(std::vector< S32 >& scenePlayers);
virtual bool setEntryFlag(S32 scenePlayerId, bool isFlag);
virtual bool addNpc(S32 npcid);
virtual bool delNpc(S32 npcid);
virtual bool findDynamicNpc(S32 npcId);
