virtual bool queryPlayerSimpleInformation(std::string& username, S32 serverId);
virtual bool queryPlayer(std::string& username, S32 playerId);
virtual bool createPlayer(std::string& username, SGE_DBPlayerData& inst, S32 serverId);
virtual bool updatePlayer(std::string& username, SGE_DBPlayerData& inst);
virtual bool deletePlayer(std::string& playername);
virtual bool queryPlayerById(std::string& name, S32 instId, S32 where);
virtual bool insertEndlessStair(S32 rank, std::string& name);
virtual bool updateEndlessStair(S32 rank, std::string& name);
virtual bool createBaby(std::string& playername, COM_BabyInst& inst, bool isToStorage);
virtual bool deleteBaby(std::string& playername, S32 babyInstId);
virtual bool updateBaby(COM_BabyInst& inst);
virtual bool updateBabys(std::string& playername, std::vector< COM_BabyInst >& babys);
virtual bool queryBabyById(std::string& name, U32 instid);
virtual bool createEmployee(std::string& playername, COM_EmployeeInst& inst);
virtual bool deleteEmployee(std::string& playername, std::vector< U32 >& instIds);
virtual bool updateEmployee(COM_EmployeeInst& inst);
virtual bool queryEmployeeById(std::string& name, U32 instid);
virtual bool insertMail(COM_Mail& mail);
virtual bool insertMailAll(COM_Mail& mail);
virtual bool insertMailByRecvs(COM_Mail& mail, std::vector< std::string >& recvs);
virtual bool fatchMail(std::string& recvName, S32 mailId);
virtual bool delMail(std::string& recvName, S32 mailId);
virtual bool updateMail(COM_Mail& mail);
virtual bool insertGuild(COM_Guild& guild, COM_GuildMember& guildMember);
virtual bool updateGuildRequestList(U32 guildId, std::vector< COM_GuildRequestData >& data);
virtual bool createGuildMember(COM_GuildMember& guildMember);
virtual bool delGuild(S32 guildId);
virtual bool updateGuildNotice(U32 guildId, std::string& notice);
virtual bool updateGuild(COM_Guild& guild);
virtual bool updateMemberPosition(S32 roleId, GuildJob job);
virtual bool updateMemberContribution(S32 roleId, S32 contribution);
virtual bool updateGuildStruction(U32 guildId, S8 level, S32 struction);
virtual bool deleteGuildMember(S32 playerId);
virtual bool insertActivity(ADType adt, SGE_SysActivity& date);
virtual bool insertLoseCharge(S32 playerId, SGE_OrderInfo& order);
virtual bool insertEmployeeQuest(U32 playerId, SGE_PlayerEmployeeQuest& data);
virtual bool delEmployeeQuest(U32 playerId);
virtual bool deleteEndlessStair(std::string& name);
