virtual bool addExp(U32 playerId, U32 exp);
virtual bool addMoney(U32 playerId, S32 money);
virtual bool addDiamond(U32 playerId, S32 diamond);
virtual bool openGM(U32 playerId);
virtual bool closeGM(U32 playerId);
virtual bool noTalkPlayer(U32 playerId, U32 time);
virtual bool sealPlayer(U32 playerId);
virtual bool kickPlayer(U32 playerId);
virtual bool openTalkPlayer(U32 playerId);
virtual bool unsealPlayer(U32 playerId);
virtual bool sendMailAllOnline(COM_Mail& mail, S32 lowLevel, S32 highLevel, S64 lowRegTime, S64 highRegTime);
virtual bool gmtNotice(NoticeSendType bType, std::string& note, U64 thetime, S64 itvtime);
virtual bool setChargeTotal(COM_ADChargeTotal& data);
virtual bool setChargeEvery(COM_ADChargeEvery& data);
virtual bool setDiscountStore(COM_ADDiscountStore& data);
virtual bool setLoginTotal(COM_ADLoginTotal& data);
virtual bool setHotRole(COM_ADHotRole& data);
virtual bool setEmployeeActivity(COM_ADEmployeeTotal& data);
virtual bool setMinGiftBagActivity(COM_ADGiftBag& data);
virtual bool setZhuanpanActivity(COM_ZhuanpanData& data);
virtual bool setIntegralshop(COM_IntegralData& data);
virtual bool makeOrder(U32 playerId, SGE_GmtOrder& order);
virtual bool doScript(std::string& script);
virtual bool playerDoScript(U32 playerId, std::string& script);
