MESSAGE(STATUS "Using linux cmake toolchain ")


SET(CMAKE_C_COMPILER "clang")
SET(CMAKE_CXX_COMPILER "clang++")
SET(CMAKE_BUILD_TYPE RELEASE CACHE STRING "RELEASE" FORCE)
SET(CMAKE_CXX_FLAGS_RELEASE "-Wall -O3 -m64 -g -std=c++11")
SET(CMAKE_C_FLAGS_RELEASE "-Wall -O3 -m64 -g")

FIND_PACKAGE(Boost COMPONENTS system filesystem REQUIRED)
INCLUDE_DIRECTORIES( ${Boost_INCLUDE_DIR} )
LINK_DIRECTORIES(${Boost_LIBRARY_DIR})


FIND_PACKAGE(ZLIB REQUIRED)
INCLUDE_DIRECTORIES( ${Zlib_INCLUDE_DIR} )
LINK_DIRECTORIES(${Zlib_LIBRARY_DIR})

FIND_PACKAGE(CURL REQUIRED)
INCLUDE_DIRECTORIES(${CURL_INCLUDE_DIR})
LINK_DIRECTORIES(${CURL_LIBRARY_DIR})

ADD_DEFINITIONS(-DUSE_MYSQL)

SET(MYSQL_LIBRARY mysqlcppconn.a)
SET(LINK_LIBRARYS ACE.a pthread dl rt z)

