
SET(CMAKE_INSTALL_PREFIX ${CMAKE_SOURCE_DIR}/../)
SET(SERVER_VERSION_MAJOR 1)
SET(SERVER_VERSION_MINOR 0)
# configure a header file to pass some of the CMake settings.
CONFIGURE_FILE("Config.h.in" "Config.h")

SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

EXECUTE_PROCESS(COMMAND ${CMAKE_SOURCE_DIR}/../Tools/genArpc.sh WORKING_DIRECTORY  ${CMAKE_SOURCE_DIR}/../Tools/)
SET(CMAKE_C_COMPILER "clang")
SET(CMAKE_CXX_COMPILER "clang++")
SET(CMAKE_BUILD_TYPE RELEASE CACHE STRING "RELEASE" FORCE)
SET(CMAKE_CXX_FLAGS_RELEASE "-Wall -O0 -m64 -g -std=c++11")
SET(CMAKE_C_FLAGS_RELEASE "-Wall -O0 -m64 -g")


FIND_PACKAGE(Boost COMPONENTS system filesystem REQUIRED)
INCLUDE_DIRECTORIES( ${Boost_INCLUDE_DIR} )
LINK_DIRECTORIES(${Boost_LIBRARY_DIR})


SET(ZLIB_ROOT $ENV{ZLIB_ROOT})
FIND_PACKAGE(ZLIB REQUIRED)
INCLUDE_DIRECTORIES( ${Zlib_INCLUDE_DIR} )
LINK_DIRECTORIES(${Zlib_LIBRARY_DIR})

SET(CURL_INCLUDE_DIR $ENV{CURL_INCLUDE_DIR})
SET(CURL_LIBRARY $ENV{CURL_LIBRARY})
FIND_PACKAGE(CURL REQUIRED)
INCLUDE_DIRECTORIES(${CURL_INCLUDE_DIR})
LINK_DIRECTORIES(${CURL_LIBRARY_DIR})
ADD_DEFINITIONS(-DUSE_MYSQL)

INCLUDE_DIRECTORIES(/opt/local/src/ACE_wrappers)
INCLUDE_DIRECTORIES(/opt/local/include/mysql56-connector-cpp/)

LINK_DIRECTORIES(/opt/local/src/ACE_wrappers/lib)
LINK_DIRECTORIES(/opt/local/lib/mysql56-connector-cpp/)
LINK_DIRECTORIES(/opt/local/lib)

SET(MYSQL_LIBRARY mysqlcppconn.a)
SET(LINK_LIBRARYS ACE.a pthread dl z)




