MESSAGE(STATUS "Using windows cmake toolchain ")


SET(CMAKE_DEBUG_POSTFIX "d")

FIND_PATH(BOOST_ROOT "-")
FIND_PATH(ACE_ROOT "-")
FIND_PATH(ZLIB_ROOT "-")
FIND_PATH(CURL_ROOT "-")
FIND_PATH(SQLITE_ROOT "-")


INCLUDE_DIRECTORIES(${ACE_ROOT})
LINK_DIRECTORIES(${ACE_ROOT}/lib)

INCLUDE_DIRECTORIES(${BOOST_ROOT})
LINK_DIRECTORIES(${BOOST_ROOT}/lib)

INCLUDE_DIRECTORIES(${SQLITE_ROOT})
LINK_DIRECTORIES(${SQLITE_ROOT})

INCLUDE_DIRECTORIES(${ZLIB_ROOT}/include)
LINK_DIRECTORIES(${ZLIB_ROOT}/lib)

INCLUDE_DIRECTORIES(${CURL_ROOT}/include)
LINK_DIRECTORIES(${CURL_ROOT}/lib)

SET(MYSQL_LIBRARY "")
SET(LINK_LIBRARYS ACEd.lib sqlite3.lib libcurld.lib wldap32.lib)

ADD_DEFINITIONS(-DUSE_SQLITE)

ADD_DEFINITIONS(-DCURL_STATICLIB)
ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)
ADD_DEFINITIONS(-DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE)


