//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
static public class Configure
{

    public static uint VersionNumber
    {
        get
        {
            return (((uint)MajorVersion.MajorNumber << 24) | ((uint)MinorVersion.MinorNumber << 16) | (uint)PatchVersion.PatchNumber);
        }
    }

    public static string Sessionkey
    {
        set
        {
            PlayerPrefs.SetString(GameManager.Instance._Account,value);
        }

        get
        {
#if UNITY_STANDALONE_WIN
            return "";
#else
			string result = PlayerPrefs.GetString(GameManager.Instance._Account);
            return null == result ? "" : result;
#endif
        }
    }

#if UNITY_EDITOR
    public static string cfgPath = "file:///" + Application.dataPath + "/../../Config/Tables/";
	public static string scriptPath = Application.dataPath + "/../../Config/Tables/LuaRoot/";
	//public static string assetsPath = "file:///" + Application.persistentDataPath + "/AssetBundlePC/";
	public static string assetsPath = "file:///" + Application.streamingAssetsPath + "/AssetBundlePC/"; //
	public static string cfgPathStn = "file:///" + Application.dataPath + "/../../Config/Tables/";
	public static string assetsPathstreaming = "file:///" + Application.streamingAssetsPath + "/AssetBundlePC/";
	public static string scriptPathStre = Application.dataPath + "/../../Config/Tables/LuaRoot/";

#elif UNITY_IOS || UNITY_IPHONE
	public static string cfgPath = "file:///" + CommonDefines.persistentDataPath + "/AssetBundleIOS/TableTemp/";
    public static string scriptPath = CommonDefines.persistentDataPath + "/AssetBundleIOS/TableTemp/LuaRoot/";
    public static string assetsPath =  "file:///" + CommonDefines.persistentDataPath + "/AssetBundleIOS/";
    public static string assetsPathstreaming = "file:///" +Application.streamingAssetsPath + "/AssetBundleIOS/";
    public static string cfgPathStn = "file:///" + Application.streamingAssetsPath + "/AssetBundleIOS/TableTemp/";
    public static string scriptPathStre = Application.streamingAssetsPath + "/AssetBundleIOS/TableTemp/LuaRoot/";

#elif UNITY_ANDROID
	// string cfgPath = Application.streamingAssetsPath + "/cfg/";

	public static string cfgPath = "file://" + Application.persistentDataPath + "/AssetBundleAndroid/TableTemp/";
	public static string scriptPath = "file://" + Application.persistentDataPath + "/AssetBundleAndroid/TableTemp/LuaRoot/";
	public static string assetsPath =  "file://" + Application.persistentDataPath + "/AssetBundleAndroid/";

	//public static string cfgPath = Application.streamingAssetsPath + "/AssetBundleAndroid/TableTemp/";
	//public static string scriptPath = Application.streamingAssetsPath + "/AssetBundleAndroid/TableTemp/LuaRoot/";
	//public static string assetsPath = Application.streamingAssetsPath + "/AssetBundleAndroid/"; //

	public static string assetsPathstreaming = Application.streamingAssetsPath + "/AssetBundleAndroid/";
	public static string cfgPathStn = Application.streamingAssetsPath + "/AssetBundleAndroid/TableTemp/";
	public static string scriptPathStre = Application.streamingAssetsPath + "/AssetBundleAndroid/TableTemp/LuaRoot/";
#else
	public static string cfgPath = "file:///" + Application.streamingAssetsPath + "/AssetBundlePC/TableTemp/";
    public static string scriptPath = Application.streamingAssetsPath + "/AssetBundlePC/TableTemp/LuaRoot/";
    public static string assetsPath = "file:///" + Application.streamingAssetsPath + "/AssetBundlePC/";
	public static string assetsPathstreaming = "file:///" + Application.streamingAssetsPath + "/AssetBundlePC/"; 
	public static string cfgPathStn =  "file:///" + Application.streamingAssetsPath + "/AssetBundlePC/TableTemp/";
	public static string scriptPathStre = Application.streamingAssetsPath + "/AssetBundlePC/TableTemp/LuaRoot/";
#endif

}


