Sys.log("main.lua");

--//script Sys.load_script("main.lua")

Sys.load_script("gmcmd.lua");
Sys.load_script("utils.lua");
Sys.load_script("skill.lua");
Sys.load_script("guidskill.lua");
Sys.load_script("battleEvent.lua");
Sys.load_script("item.lua");
Sys.load_script("../Tables/LuaRoot/lua/global.lua");
Sys.load_script("GameEvent.lua");
Sys.load_script("notice.lua");
Sys.load_script("Achievement.lua");

--BOSS的
Sys.load_script("AI/BaiEMoJiLaSi_BOSS.lua");
Sys.load_script("AI/BaiEMoJiLaSi_BOSS2.lua");
Sys.load_script("AI/CiKeAYi_BOSS.lua");
Sys.load_script("AI/CiKeFenShen_BOSS.lua");
Sys.load_script("AI/DaodanGui_BOSS.lua");
Sys.load_script("AI/ELangXiSi_BOSS.lua");
Sys.load_script("AI/EMoShiRenHua_BOSS.lua");
Sys.load_script("AI/HaiJuLong_BOSS.lua");
Sys.load_script("AI/JiangShiShiYanTi_BOSS.lua");
Sys.load_script("AI/JuRenBaLuoSi_BOSS.lua");
Sys.load_script("AI/JuXiong_BOSS.lua");
Sys.load_script("AI/NiuTouGuai_BOSS.lua");
Sys.load_script("AI/ShiRenMoAoZi_BOSS.lua");
Sys.load_script("AI/ShiRenMoFaShiBoKan_BOSS.lua");
Sys.load_script("AI/ShiRenMoShouLingLuoKe_BOSS.lua");
Sys.load_script("AI/XiYiRenZhaGe_BOSS.lua");
Sys.load_script("AI/YinYing_BOSS.lua");
Sys.load_script("AI/ZhaDanMo_BOSS.lua");
Sys.load_script("AI/BianSeLongLuoDi_Boss.lua");
Sys.load_script("AI/BingLangJiaNeiTe_Boss.lua");
Sys.load_script("AI/DaXiongMaoLuTe_Boss.lua");
Sys.load_script("AI/DesertDanditBaTuo_Boss.lua");
Sys.load_script("AI/DesertGoanna_Boss.lua");
Sys.load_script("AI/DesertTunShiHua_Boss.lua");
Sys.load_script("AI/DuoMo_Boss.lua");
Sys.load_script("AI/EMoShiTuLuoErDan_Boss.lua");
Sys.load_script("AI/HeiAnMoJunBaLiKe_Boss.lua");
Sys.load_script("AI/JunFaPiNiSi_Boss.lua");
Sys.load_script("AI/JuXingSiWangRuoChong_Boss.lua");
Sys.load_script("AI/QianNianBingJingShuMo_Boss.lua");
Sys.load_script("AI/QianNianXueYao_Boss.lua");
Sys.load_script("AI/ShaJuLongAoMaJiTe_Boss.lua");
Sys.load_script("AI/ShaYingCiKeDaShiLuoSaier_Boss.lua");
Sys.load_script("AI/ShiMoXiangKeLuTe_Boss.lua");
Sys.load_script("AI/SiLingFaShiKeTuo_Boss.lua");
Sys.load_script("AI/WuYaoKeJiaSuErDe_Boss.lua");
Sys.load_script("AI/XieZiKingAKS_Boss.lua");
Sys.load_script("AI/XiYiRenMoLuo_Boss.lua");
Sys.load_script("AI/XiYiRenZhiWangKangNuo_Boss.lua");
Sys.load_script("AI/YinLongAiWeiDa_Boss.lua");

Sys.load_script("AI/DefaultPlayer.lua");
Sys.load_script("AI/MonsterEvent.lua");

--伙伴的
Sys.load_script("EmployeeAI/gongshou.lua");
Sys.load_script("EmployeeAI/gongshou1.lua");
Sys.load_script("EmployeeAI/gedou.lua");
Sys.load_script("EmployeeAI/gedou1.lua");
Sys.load_script("EmployeeAI/zhanfu.lua");
Sys.load_script("EmployeeAI/zhanfu1.lua");
Sys.load_script("EmployeeAI/chuanjiao.lua");
Sys.load_script("EmployeeAI/chuanjiao1.lua");
Sys.load_script("EmployeeAI/wushi.lua");
Sys.load_script("EmployeeAI/wushi1.lua");
Sys.load_script("EmployeeAI/zhoushu.lua");
Sys.load_script("EmployeeAI/zhoushu1.lua");
Sys.load_script("EmployeeAI/fashi.lua");
Sys.load_script("EmployeeAI/fashi1.lua");
Sys.load_script("EmployeeAI/renzhe.lua");
Sys.load_script("EmployeeAI/qishi.lua");
Sys.load_script("EmployeeAI/qishi1.lua");
Sys.load_script("EmployeeAI/jianshi.lua");
Sys.load_script("EmployeeAI/jianshi1.lua");

Sys.load_script("quest.lua");
Sys.load_script("activity.lua");
Sys.load_script("sys.lua");